In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
df=pd.read_csv('food.csv')
df.head()
for col in ['Price', 'Quantity']:
    df[col]=df[col].replace(',','',regex=True).astype(float)
df.head()
num_features = ["Price"]
cat_features = ["Product", "Purchase Type", "Payment Method", "Manager", "City"]


num_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])
preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_transformer, ["Price", "Quantity"]),
        ("cat", cat_transformer, ["Product", "Purchase Type", "Payment Method", "Manager", "City"])
    ])

preprocessor.set_output(transform="pandas")
data_preprocessed = preprocessor.fit_transform(df)
print(data_preprocessed.head())

X = data_preprocessed
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X,
y, test_size=0.2, random_state=42)


print(X_train.head())
print(y_train.head())

   num__Price  num__Quantity  cat__Product_Beverages  cat__Product_Burgers  \
0   -0.833620       0.524367                     0.0                   0.0
1   -0.958236       1.329579                     1.0                   0.0
2   -0.487463      -1.213303                     0.0                   0.0
3    1.358705       0.508514                     0.0                   1.0
4    0.657161      -1.210459                     0.0                   0.0

   cat__Product_Chicken Sandwiches  cat__Product_Fries  \
0                              0.0                 1.0
1                              0.0                 0.0
2                              0.0                 0.0
3                              0.0                 0.0
4                              1.0                 0.0

   cat__Product_Sides & Other  cat__Purchase Type_Drive-thru   \
0                         0.0                             0.0
1                         0.0                             0.0
2                         1.0                             0.0
3                         0.0                             0.0
4                         0.0                             0.0

   cat__Purchase Type_In-store   cat__Purchase Type_Online   ...  \
0                           0.0                         1.0  ...
1                           0.0                         1.0  ...
2                           1.0                         0.0  ...
3                           1.0                         0.0  ...
4                           1.0                         0.0  ...

   cat__Manager_Remy    Monet  cat__Manager_Remy Monet  \
0                         0.0                      0.0
1                         0.0                      0.0
2                         0.0                      0.0
3                         0.0                      0.0
4                         0.0                      0.0

   cat__Manager_Tom      Jackson  cat__Manager_Tom Jackson  \
0                            1.0                       0.0
1                            0.0                       0.0
2                            0.0                       0.0
3                            0.0                       0.0
4                            0.0                       0.0

   cat__Manager_Walter Muller  cat__City_Berlin  cat__City_Lisbon  \
0                         0.0               0.0               0.0
1                         0.0               0.0               0.0
2                         0.0               0.0               1.0
3                         1.0               1.0               0.0
4                         1.0               1.0               0.0

   cat__City_London  cat__City_Madrid  cat__City_Paris
0               1.0               0.0              0.0
1               0.0               1.0              0.0
2               0.0               0.0              0.0
3               0.0               0.0              0.0
4               0.0               0.0              0.0

[5 rows x 32 columns]
     num__Price  num__Quantity  cat__Product_Beverages  cat__Product_Burgers  \
38     1.358705       0.221334                     0.0                   1.0
143   -0.958236       1.013491                     1.0                   0.0
84    -0.487463      -1.213303                     0.0                   0.0
55    -0.833620       1.058766                     0.0                   0.0
218   -0.958236       1.329579                     1.0                   0.0

     cat__Product_Chicken Sandwiches  cat__Product_Fries  \
38                               0.0                 0.0
143                              0.0                 0.0
84                               0.0                 0.0
55                               0.0                 1.0
218                              0.0                 0.0

     cat__Product_Sides & Other  cat__Purchase Type_Drive-thru   \
38                          0.0                             0.0
143                         0.0                             0.0
84                          1.0                             1.0
55                          0.0                             1.0
218                         0.0                             0.0

     cat__Purchase Type_In-store   cat__Purchase Type_Online   ...  \
38                            1.0                         0.0  ...
143                           0.0                         1.0  ...
84                            0.0                         0.0  ...
55                            0.0                         0.0  ...
218                           1.0                         0.0  ...

     cat__Manager_Remy    Monet  cat__Manager_Remy Monet  \
38                          0.0                      0.0
143                         0.0                      0.0
84                          0.0                      0.0
55                          0.0                      0.0
218                         0.0                      0.0

     cat__Manager_Tom      Jackson  cat__Manager_Tom Jackson  \
38                             0.0                       0.0
143                            0.0                       1.0
84                             0.0                       1.0
55                             0.0                       0.0
218                            0.0                       0.0

     cat__Manager_Walter Muller  cat__City_Berlin  cat__City_Lisbon  \
38                          0.0               0.0               0.0
143                         0.0               0.0               0.0
84                          0.0               0.0               0.0
55                          0.0               0.0               1.0
218                         0.0               0.0               1.0

     cat__City_London  cat__City_Madrid  cat__City_Paris
38                0.0               1.0              0.0
143               1.0               0.0              0.0
84                1.0               0.0              0.0
55                0.0               0.0              0.0
218               0.0               0.0              0.0

[5 rows x 32 columns]
38     12.99
143     2.95
84      4.99
55      3.49
218     2.95
Name: Price, dtype: float64